import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

export default function Home({ movies }) {
  console.log(movies);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Prisma Data Fetching</h1>

        {movies.map((movi, index) => (
          <div key={index}>
            <h2>Movie {movi.title}</h2>
            <h4>Movie {movi.date}</h4>
          </div>
        ))}
      </main>
    </div>
  );
}

export async function getServerSideProps() {
  const movies = await prisma.movies.findMany();

  return {
    props: {
      movies,
    },
  };
}
